name: "publish"

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish packages

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          6.0.x
          7.0.x

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release -o ./Releases --no-restore

    - name: Publish packages 
      run: dotnet nuget push *.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
      working-directory: Releases
